import { SemanticTokensDeltaRequest, SemanticTokensRangeRequest } from 'vscode-languageserver'
import {
  CallHierarchyIncomingCallsRequest,
  CallHierarchyOutgoingCallsRequest,
  CodeActionRequest, CodeActionResolveRequest, CodeLensRequest, CodeLensResolveRequest, CompletionRequest,
  CompletionResolveRequest, DefinitionRequest, DocumentColorRequest, DocumentDiagnosticRequest, DocumentFormattingRequest, DocumentHighlightRequest, DocumentLinkRequest,
  DocumentLinkResolveRequest, DocumentOnTypeFormattingRequest, DocumentRangeFormattingRequest, DocumentSymbolRequest, ExecuteCommandRequest,
  FoldingRangeRequest, HoverRequest, ImplementationRequest, InlayHintRequest, InlayHintResolveRequest, InlineValueRequest, LinkedEditingRangeRequest, MonikerRequest, PrepareRenameRequest, ReferencesRequest, RenameRequest, RequestType, SelectionRangeRequest, SemanticTokensRequest,
  SignatureHelpRequest, TypeDefinitionRequest, TypeHierarchyPrepareRequest, TypeHierarchySubtypesRequest, TypeHierarchySupertypesRequest, WorkspaceDiagnosticRequest, WorkspaceSymbolRequest, WorkspaceSymbolResolveRequest
} from 'vscode-languageserver-protocol'

export const forwardedClientRequests: RequestType<unknown, unknown, unknown>[] = [
  CallHierarchyIncomingCallsRequest.type,
  CallHierarchyOutgoingCallsRequest.type,
  CodeActionRequest.type,
  CodeActionResolveRequest.type,
  CodeLensRequest.type,
  CodeLensResolveRequest.type,
  CompletionRequest.type,
  CompletionResolveRequest.type,
  DefinitionRequest.type,
  DocumentColorRequest.type,
  DocumentDiagnosticRequest.type,
  DocumentFormattingRequest.type,
  DocumentHighlightRequest.type,
  DocumentLinkRequest.type,
  DocumentLinkResolveRequest.type,
  DocumentOnTypeFormattingRequest.type,
  DocumentRangeFormattingRequest.type,
  DocumentSymbolRequest.type,
  ExecuteCommandRequest.type,
  FoldingRangeRequest.type,
  HoverRequest.type,
  ImplementationRequest.type,
  InlayHintRequest.type,
  InlayHintResolveRequest.type,
  InlineValueRequest.type,
  LinkedEditingRangeRequest.type,
  MonikerRequest.type,
  PrepareRenameRequest.type,
  ReferencesRequest.type,
  ReferencesRequest.type,
  RenameRequest.type,
  SelectionRangeRequest.type,
  SemanticTokensDeltaRequest.type,
  SemanticTokensDeltaRequest.type,
  SemanticTokensRangeRequest.type,
  SemanticTokensRequest.type,
  SignatureHelpRequest.type,
  TypeDefinitionRequest.type,
  TypeHierarchyPrepareRequest.type,
  TypeHierarchySubtypesRequest.type,
  TypeHierarchySupertypesRequest.type,
  WorkspaceDiagnosticRequest.type,
  WorkspaceSymbolRequest.type,
  WorkspaceSymbolResolveRequest.type
]
